export enum IconName {
  Github = "github",
  Linkedin = "linkedin",
  Twitter = "twitter",
  Email = "email",
  Website = "website",
  React = "react",
  Nextjs = "nextjs",
  Tailwindcss = "tailwindcss",
  Typescript = "typescript",
  Javascript = "javascript",
  Nodejs = "nodejs",
  Mongodb = "mongodb",
  Expressjs = "expressjs",
  Graphql = "graphql",
  Chakraui = "chakraui",
  Sass = "sass",
  FramerMotion = "framer-motion",
  Redux = "redux",
  Webpack = "webpack",
  Npm = "npm",
  Firebase = "firebase",
  Vite = "vite",
  Live = "live",
  Next = "next",
}
